### ISSUE TITLE
Crash on [VSLCall toggleMute:NSError**] (pjsua_conf_disconnect / pjsua_conf_connect) throws an assertion

### ISSUE THREAD

**Issue by kesslermichael** [VoIPGRID/VialerSIPLib#176]
### Version

3.5.1

### File / Feature

Toggle mute during a call

### Expected behavior

The call should be muted/unmuted without crashing the app (or throwing assertions)

### Actual behavior

An assertion is thrown when calling `VSLCallManager.toggleMute(for: call)`
Usually it works for the first time and throws the assertion on the second or third call to this function.

### Stacktrace / Error message

**Stacktrace:**
../src/pjmedia/conference.c, line 971
..
..
-[VSLCall toggleMute:&error]
pjsua_conf_connect(source, sink)
..
..
-[VSLCallManager toggleMuteForCall:call completion:completion]
VSLCallManager.toggleMute(for: call) // called from Swift code

**Log:**
> pjsua_aud.c !Conf connect: 0 --> -1
> Assertion failed: (conf && src_slot<conf->max_ports && sink_slot<conf->max_ports), function pjmedia_conf_connect_port, file ../src/pjmedia/conference.c, line 971.

### Other info

* Swift project
* Linking the framework with CocoaPods
* Deployment target: iOS 10
* Tested in debug mode on iPhone X device, iOS 12.1.4
* Codec: speex/8000
* Transport: TLS
* Audio call (video not enabled at all)

Reproduced in example app that comes with the framework 
**Steps to reproduce** (in the example app):
* Launch the app
* Register to SIP
* Make a voice only call 
* Perform few mute/unmute calls (tap 'Mute' -> 'Muted' -> 'Mute' etc.) until the app will crash/assert (usually occurs on 2-nd/3-rd try)

**Comment by invisible66** [comment]
You can try #165.

**Comment by jeremynorman89** [comment]
I've created a pull request #178  where this issue should be resolved (at least it should no longer crash). If you're able to verify that this resolved the issue it would be appreciated.

**Comment by kesslermichael** [comment]
> You can try #165.

This doesn't solve the crash/assertion

**Comment by kesslermichael** [comment]
> I've created a pull request #178 where this issue should be resolved (at least it should no longer crash). If you're able to verify that this resolved the issue it would be appreciated.

This doesn't solve the crash/assertion 
Have you tried to play with it on the sample project? 
Just try to mute -> unmute -> mute -> unmute etc. (even not fast - once a second or so) until it gets the assertion..
